args:
    device: 'cuda'
    results_dir: './2D_ns_next_step/'
    num_workers: 0
    batch_size: 8
    #initial_step: 1
    initial_step: 41
    rollout_length: 5
    t_train: 200
    validate: 1

    data_name: '2d_ns_1s_256_4eq.h5'
    #data_name: '2d_ns_30s_256_370eq.h5'
    #data_name: '2d_electric_100_60.h5'
    
    train_style: 'next_step'
    #train_style: 'fixed_future'
    
    #split_style: 'equation'
    split_style: 'initial_condition'

    base_path: './2D_NS_DATA/'
    return_text: True
    reduced_resolution: 4
    reduced_resolution_t: 1
    reduced_batch: 1

    # Optimizer
    learning_rate: 1.e-3
    weight_decay: 0.
    scheduler_step: 10
    scheduler_gamma: 0.5
    epochs: 11
    num_seeds: 2

    # Sim samples
    num_t: 100
    num_x: 64
    num_y: 64
    #num_x: 60
    #num_y: 100
    
    #sim_time: 80
    #sim_time: 120
    sim_time: 999

    num_samples: 4
    #num_samples: 200
    #num_samples: 370
    #num_samples: 5000

    samples_per_equation: 1
    #samples_per_equation: 5

    # Encoder
    input_channels: 43    # Number of frames?
    heads: 4
    in_emb_dim: 128       # num_x
    out_seq_emb_dim: 128  # Embedding
    depth: 2              # Number of layers
    #dropout: 0.05          # Maybe not necessary
    dropout: 0.          # Maybe not necessary
    #enc_res: 2048             # Not sure
    enc_res: 128             # Not sure

    # Decoder
    latent_channels: 128  # 256??
    out_channels: 1       # 1D output
    decoding_depth: 1     # Number of layers
    scale: 8              # Not sure
    #dec_res: 2048             # Not sure
    dec_res: 128             # Not sure

    # Tracking
    log_freq: 1
    progress_plot_freq: 10
